export const product = [
  {
    id: 1,
    name: "Штурмовая винтовка",
    price: "500р",
    description: "This is a sample product description.",
    quantity: "1",
    image: "src/image/rifle.ak.png",
    category: "gun",
  },
  {
    id: 2,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "src/image/rifle.bolt.png",
    category: "comps",
  },
  {
    id: 3,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 4,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 5,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    catecories: "gun",
    image: "",
  },
  {
    id: 6,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    catecories: "comps",
    image: "",
  },
  {
    id: 7,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 8,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 9,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 10,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 11,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 12,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 13,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
  {
    id: 14,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
  },
];
