export const product = [
  {
    id: 1,
    name: "Штурмовая винтовка",
    price: "500р",
    description: "This is a sample product description.",
    quantity: "1",
    image: "src/image/rifle.ak.png",
    category: "gun",
  },
  {
    id: 2,
    name: "Старые микросхемы",
    price: "104р",
    description: "This is a sample product description.",
    image: "src/image/techparts.png",
    category: "comps",
  },
  {
    id: 3,
    name: "Железная маска",
    price: 29.99,
    description: "This is a sample product description.",
    image: "src/image/metal.facemask.png",
    category: "armor",
  },
  {
    id: 4,
    name: "Патрон 5.56-мм",
    price: 29.99,
    description: "This is a sample product description.",
    image: "src/image/ammo.rifle.png",
    category: "ammo",
  },
  {
    id: 5,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "src/image/stones.png",
    category: "resurce",
  },
  {
    id: 6,
    name: "Большые каменные ворота",
    price: 29.99,
    description: "This is a sample product description.",
    catecories: "comps",
    image: "src/image/gates.external.high.stone.png",
    category: "build",
  },
  {
    id: 7,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "src/image/icepick.salvaged.png",
    category: "tools",
  },
  {
    id: 8,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
  {
    id: 9,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
  {
    id: 10,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
  {
    id: 11,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
  {
    id: 12,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
  {
    id: 13,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
  {
    id: 14,
    name: "Sample Product",
    price: 29.99,
    description: "This is a sample product description.",
    image: "",
    category: "",
  },
];